// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package codec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerMessage struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerMessage)(nil), "codec.ServerMessage")
	proto.RegisterType((*Task)(nil), "codec.Task")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0xce, 0x82, 0x30,
	0x14, 0x85, 0x03, 0xff, 0x8f, 0xc6, 0xa2, 0x0e, 0x9d, 0x3a, 0x22, 0x83, 0x61, 0x6a, 0x0d, 0xbe,
	0x81, 0xbb, 0x0b, 0x3a, 0xb9, 0x5d, 0xca, 0x0d, 0x36, 0x44, 0x6e, 0xd3, 0x5e, 0x7d, 0x7e, 0x63,
	0x8d, 0xe3, 0xf7, 0x9d, 0x93, 0x9c, 0x23, 0xd6, 0x11, 0xc3, 0x0b, 0x83, 0xf6, 0x81, 0x98, 0x64,
	0x61, 0x69, 0x40, 0x5b, 0xb7, 0x62, 0x73, 0x49, 0xfa, 0x8c, 0x31, 0xc2, 0x88, 0x72, 0x27, 0x0a,
	0x86, 0x38, 0x45, 0x95, 0x55, 0x7f, 0x4d, 0xd9, 0x96, 0x3a, 0xf5, 0xf4, 0x15, 0xe2, 0xd4, 0x7d,
	0x93, 0xfa, 0x20, 0xfe, 0x3f, 0x28, 0xb7, 0x22, 0x77, 0x83, 0xca, 0xaa, 0xac, 0x59, 0x75, 0xb9,
	0x1b, 0xa4, 0x12, 0x4b, 0x4b, 0x33, 0xe3, 0xcc, 0x2a, 0x4f, 0xf2, 0x87, 0xa7, 0xe6, 0xb6, 0x1f,
	0x1d, 0xdf, 0x9f, 0xbd, 0xb6, 0xf4, 0x30, 0x93, 0x85, 0x10, 0x90, 0x99, 0x8c, 0x87, 0x00, 0x23,
	0xcd, 0x06, 0xbc, 0x33, 0x69, 0xa7, 0x5f, 0xa4, 0x77, 0xc7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xee, 0x57, 0xdc, 0xf8, 0xad, 0x00, 0x00, 0x00,
}
