export {default as XAdminView} from './XAdminView';
export {default as XJobView} from './XJobView';
export {default as XLogin} from './XLogin';
export {default as XMultiFileView} from './XMultiFileView';
export {default as XMultiJobView, MULTI_JOB_QUERY} from './XMultiJobView';
export {default as XMultiTagView, MULTI_TAG_QUERY} from './XMultiTagView';
export {default as XMultiTargetView, MULTI_TARGET_QUERY} from './XMultiTargetView';
export {default as XProfileView} from './XProfileView';
export {default as XTargetView, TARGET_QUERY} from './XTargetView';
export {default as XTaskView} from './XTaskView';
