// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kcarretto/paragon/ent/job"
	"github.com/kcarretto/paragon/ent/tag"
	"github.com/kcarretto/paragon/ent/target"
	"github.com/kcarretto/paragon/ent/task"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetQueueTime sets the "QueueTime" field.
func (tc *TaskCreate) SetQueueTime(t time.Time) *TaskCreate {
	tc.mutation.SetQueueTime(t)
	return tc
}

// SetNillableQueueTime sets the "QueueTime" field if the given value is not nil.
func (tc *TaskCreate) SetNillableQueueTime(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetQueueTime(*t)
	}
	return tc
}

// SetLastChangedTime sets the "LastChangedTime" field.
func (tc *TaskCreate) SetLastChangedTime(t time.Time) *TaskCreate {
	tc.mutation.SetLastChangedTime(t)
	return tc
}

// SetClaimTime sets the "ClaimTime" field.
func (tc *TaskCreate) SetClaimTime(t time.Time) *TaskCreate {
	tc.mutation.SetClaimTime(t)
	return tc
}

// SetNillableClaimTime sets the "ClaimTime" field if the given value is not nil.
func (tc *TaskCreate) SetNillableClaimTime(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetClaimTime(*t)
	}
	return tc
}

// SetExecStartTime sets the "ExecStartTime" field.
func (tc *TaskCreate) SetExecStartTime(t time.Time) *TaskCreate {
	tc.mutation.SetExecStartTime(t)
	return tc
}

// SetNillableExecStartTime sets the "ExecStartTime" field if the given value is not nil.
func (tc *TaskCreate) SetNillableExecStartTime(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetExecStartTime(*t)
	}
	return tc
}

// SetExecStopTime sets the "ExecStopTime" field.
func (tc *TaskCreate) SetExecStopTime(t time.Time) *TaskCreate {
	tc.mutation.SetExecStopTime(t)
	return tc
}

// SetNillableExecStopTime sets the "ExecStopTime" field if the given value is not nil.
func (tc *TaskCreate) SetNillableExecStopTime(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetExecStopTime(*t)
	}
	return tc
}

// SetContent sets the "Content" field.
func (tc *TaskCreate) SetContent(s string) *TaskCreate {
	tc.mutation.SetContent(s)
	return tc
}

// SetOutput sets the "Output" field.
func (tc *TaskCreate) SetOutput(s string) *TaskCreate {
	tc.mutation.SetOutput(s)
	return tc
}

// SetNillableOutput sets the "Output" field if the given value is not nil.
func (tc *TaskCreate) SetNillableOutput(s *string) *TaskCreate {
	if s != nil {
		tc.SetOutput(*s)
	}
	return tc
}

// SetError sets the "Error" field.
func (tc *TaskCreate) SetError(s string) *TaskCreate {
	tc.mutation.SetError(s)
	return tc
}

// SetNillableError sets the "Error" field if the given value is not nil.
func (tc *TaskCreate) SetNillableError(s *string) *TaskCreate {
	if s != nil {
		tc.SetError(*s)
	}
	return tc
}

// SetSessionID sets the "SessionID" field.
func (tc *TaskCreate) SetSessionID(s string) *TaskCreate {
	tc.mutation.SetSessionID(s)
	return tc
}

// SetNillableSessionID sets the "SessionID" field if the given value is not nil.
func (tc *TaskCreate) SetNillableSessionID(s *string) *TaskCreate {
	if s != nil {
		tc.SetSessionID(*s)
	}
	return tc
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (tc *TaskCreate) AddTagIDs(ids ...int) *TaskCreate {
	tc.mutation.AddTagIDs(ids...)
	return tc
}

// AddTags adds the "tags" edges to the Tag entity.
func (tc *TaskCreate) AddTags(t ...*Tag) *TaskCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tc.AddTagIDs(ids...)
}

// SetJobID sets the "job" edge to the Job entity by ID.
func (tc *TaskCreate) SetJobID(id int) *TaskCreate {
	tc.mutation.SetJobID(id)
	return tc
}

// SetJob sets the "job" edge to the Job entity.
func (tc *TaskCreate) SetJob(j *Job) *TaskCreate {
	return tc.SetJobID(j.ID)
}

// SetTargetID sets the "target" edge to the Target entity by ID.
func (tc *TaskCreate) SetTargetID(id int) *TaskCreate {
	tc.mutation.SetTargetID(id)
	return tc
}

// SetNillableTargetID sets the "target" edge to the Target entity by ID if the given value is not nil.
func (tc *TaskCreate) SetNillableTargetID(id *int) *TaskCreate {
	if id != nil {
		tc = tc.SetTargetID(*id)
	}
	return tc
}

// SetTarget sets the "target" edge to the Target entity.
func (tc *TaskCreate) SetTarget(t *Target) *TaskCreate {
	return tc.SetTargetID(t.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	var (
		err  error
		node *Task
	)
	tc.defaults()
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.QueueTime(); !ok {
		v := task.DefaultQueueTime()
		tc.mutation.SetQueueTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.QueueTime(); !ok {
		return &ValidationError{Name: "QueueTime", err: errors.New(`ent: missing required field "Task.QueueTime"`)}
	}
	if _, ok := tc.mutation.LastChangedTime(); !ok {
		return &ValidationError{Name: "LastChangedTime", err: errors.New(`ent: missing required field "Task.LastChangedTime"`)}
	}
	if _, ok := tc.mutation.Content(); !ok {
		return &ValidationError{Name: "Content", err: errors.New(`ent: missing required field "Task.Content"`)}
	}
	if v, ok := tc.mutation.Content(); ok {
		if err := task.ContentValidator(v); err != nil {
			return &ValidationError{Name: "Content", err: fmt.Errorf(`ent: validator failed for field "Task.Content": %w`, err)}
		}
	}
	if v, ok := tc.mutation.SessionID(); ok {
		if err := task.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "SessionID", err: fmt.Errorf(`ent: validator failed for field "Task.SessionID": %w`, err)}
		}
	}
	if _, ok := tc.mutation.JobID(); !ok {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required edge "Task.job"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: task.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: task.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.QueueTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldQueueTime,
		})
		_node.QueueTime = value
	}
	if value, ok := tc.mutation.LastChangedTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldLastChangedTime,
		})
		_node.LastChangedTime = value
	}
	if value, ok := tc.mutation.ClaimTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldClaimTime,
		})
		_node.ClaimTime = value
	}
	if value, ok := tc.mutation.ExecStartTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldExecStartTime,
		})
		_node.ExecStartTime = value
	}
	if value, ok := tc.mutation.ExecStopTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldExecStopTime,
		})
		_node.ExecStopTime = value
	}
	if value, ok := tc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := tc.mutation.Output(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldOutput,
		})
		_node.Output = value
	}
	if value, ok := tc.mutation.Error(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldError,
		})
		_node.Error = value
	}
	if value, ok := tc.mutation.SessionID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldSessionID,
		})
		_node.SessionID = value
	}
	if nodes := tc.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.TagsTable,
			Columns: task.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tag.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.JobTable,
			Columns: []string{task.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: job.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.job_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.TargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.TargetTable,
			Columns: []string{task.TargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: target.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.target_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
