// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kcarretto/paragon/ent/job"
	"github.com/kcarretto/paragon/ent/target"
	"github.com/kcarretto/paragon/ent/task"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// QueueTime holds the value of the "QueueTime" field.
	// The timestamp for when the Task was queued/created
	QueueTime time.Time `json:"QueueTime,omitempty"`
	// LastChangedTime holds the value of the "LastChangedTime" field.
	// The timestamp for when the Task was last changed
	LastChangedTime time.Time `json:"LastChangedTime,omitempty"`
	// ClaimTime holds the value of the "ClaimTime" field.
	// The timestamp for when the Task was claim
	ClaimTime time.Time `json:"ClaimTime,omitempty"`
	// ExecStartTime holds the value of the "ExecStartTime" field.
	// The timestamp for when the Task was executed
	ExecStartTime time.Time `json:"ExecStartTime,omitempty"`
	// ExecStopTime holds the value of the "ExecStopTime" field.
	// The timestamp for when the Task's execution ended
	ExecStopTime time.Time `json:"ExecStopTime,omitempty"`
	// Content holds the value of the "Content" field.
	// The content of the task (usually a Renegade Script)
	Content string `json:"Content,omitempty"`
	// Output holds the value of the "Output" field.
	// The output from executing the task
	Output string `json:"Output,omitempty"`
	// Error holds the value of the "Error" field.
	// The error, if any, produced while executing the Task
	Error string `json:"Error,omitempty"`
	// SessionID holds the value of the "SessionID" field.
	SessionID string `json:"SessionID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	job_tasks    *int
	target_tasks *int
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Job holds the value of the job edge.
	Job *Job `json:"job,omitempty"`
	// Target holds the value of the target edge.
	Target *Target `json:"target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) JobOrErr() (*Job, error) {
	if e.loadedTypes[1] {
		if e.Job == nil {
			// The edge job was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: job.Label}
		}
		return e.Job, nil
	}
	return nil, &NotLoadedError{edge: "job"}
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) TargetOrErr() (*Target, error) {
	if e.loadedTypes[2] {
		if e.Target == nil {
			// The edge target was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: target.Label}
		}
		return e.Target, nil
	}
	return nil, &NotLoadedError{edge: "target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			values[i] = new(sql.NullInt64)
		case task.FieldContent, task.FieldOutput, task.FieldError, task.FieldSessionID:
			values[i] = new(sql.NullString)
		case task.FieldQueueTime, task.FieldLastChangedTime, task.FieldClaimTime, task.FieldExecStartTime, task.FieldExecStopTime:
			values[i] = new(sql.NullTime)
		case task.ForeignKeys[0]: // job_tasks
			values[i] = new(sql.NullInt64)
		case task.ForeignKeys[1]: // target_tasks
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Task", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (t *Task) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case task.FieldQueueTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field QueueTime", values[i])
			} else if value.Valid {
				t.QueueTime = value.Time
			}
		case task.FieldLastChangedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field LastChangedTime", values[i])
			} else if value.Valid {
				t.LastChangedTime = value.Time
			}
		case task.FieldClaimTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ClaimTime", values[i])
			} else if value.Valid {
				t.ClaimTime = value.Time
			}
		case task.FieldExecStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ExecStartTime", values[i])
			} else if value.Valid {
				t.ExecStartTime = value.Time
			}
		case task.FieldExecStopTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ExecStopTime", values[i])
			} else if value.Valid {
				t.ExecStopTime = value.Time
			}
		case task.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Content", values[i])
			} else if value.Valid {
				t.Content = value.String
			}
		case task.FieldOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Output", values[i])
			} else if value.Valid {
				t.Output = value.String
			}
		case task.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Error", values[i])
			} else if value.Valid {
				t.Error = value.String
			}
		case task.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field SessionID", values[i])
			} else if value.Valid {
				t.SessionID = value.String
			}
		case task.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field job_tasks", value)
			} else if value.Valid {
				t.job_tasks = new(int)
				*t.job_tasks = int(value.Int64)
			}
		case task.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field target_tasks", value)
			} else if value.Valid {
				t.target_tasks = new(int)
				*t.target_tasks = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryTags queries the "tags" edge of the Task entity.
func (t *Task) QueryTags() *TagQuery {
	return (&TaskClient{config: t.config}).QueryTags(t)
}

// QueryJob queries the "job" edge of the Task entity.
func (t *Task) QueryJob() *JobQuery {
	return (&TaskClient{config: t.config}).QueryJob(t)
}

// QueryTarget queries the "target" edge of the Task entity.
func (t *Task) QueryTarget() *TargetQuery {
	return (&TaskClient{config: t.config}).QueryTarget(t)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Task) Update() *TaskUpdateOne {
	return (&TaskClient{config: t.config}).UpdateOne(t)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Task) Unwrap() *Task {
	tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	t.config.driver = tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v", t.ID))
	builder.WriteString(", QueueTime=")
	builder.WriteString(t.QueueTime.Format(time.ANSIC))
	builder.WriteString(", LastChangedTime=")
	builder.WriteString(t.LastChangedTime.Format(time.ANSIC))
	builder.WriteString(", ClaimTime=")
	builder.WriteString(t.ClaimTime.Format(time.ANSIC))
	builder.WriteString(", ExecStartTime=")
	builder.WriteString(t.ExecStartTime.Format(time.ANSIC))
	builder.WriteString(", ExecStopTime=")
	builder.WriteString(t.ExecStopTime.Format(time.ANSIC))
	builder.WriteString(", Content=")
	builder.WriteString(t.Content)
	builder.WriteString(", Output=")
	builder.WriteString(t.Output)
	builder.WriteString(", Error=")
	builder.WriteString(t.Error)
	builder.WriteString(", SessionID=")
	builder.WriteString(t.SessionID)
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task

func (t Tasks) config(cfg config) {
	for _i := range t {
		t[_i].config = cfg
	}
}
