// Code generated by entc, DO NOT EDIT.

package credential

import (
	"github.com/kcarretto/paragon/ent/schema"
)

const (
	// Label holds the string label denoting the credential type in the database.
	Label = "credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrincipal holds the string denoting the principal vertex property in the database.
	FieldPrincipal = "principal"
	// FieldSecret holds the string denoting the secret vertex property in the database.
	FieldSecret = "secret"
	// FieldType holds the string denoting the type vertex property in the database.
	FieldType = "type"
	// FieldFails holds the string denoting the fails vertex property in the database.
	FieldFails = "fails"

	// Table holds the table name of the credential in the database.
	Table = "credentials"
)

// Columns holds all SQL columns are credential fields.
var Columns = []string{
	FieldID,
	FieldPrincipal,
	FieldSecret,
	FieldType,
	FieldFails,
}

var (
	fields = schema.Credential{}.Fields()

	// descFails is the schema descriptor for fails field.
	descFails = fields[3].Descriptor()
	// DefaultFails holds the default value on creation for the fails field.
	DefaultFails = descFails.Default.(int)
	// FailsValidator is a validator for the "fails" field. It is called by the builders before save.
	FailsValidator = descFails.Validators[0].(func(int) error)
)
